version: '3.9'

services:
  app:
    container_name: busrush
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/busrush
    # environment:
    #  FLASK_DEBUG: True
    networks:
      - bus-net
  db:
    container_name: busrush-db
    image: mysql/mysql-server:5.7
    ports:
      - '3306:3306'
    volumes:
      - busrush-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: busrush
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - bus-net
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - type: bind
        source: ./rabbitmq-enabled-plugins
        target: /etc/rabbitmq/enabled_plugins
      - type: bind
        source: ./rabbitmq.config
        target: /etc/rabbitmq/rabbitmq.config
      - type: bind
        source: ./rabbitmq-defs.json
        target: /etc/rabbitmq/rabbitmq-defs.json
    networks:
      - bus-net
  cassandra:
    container_name: cassandra
    image: cassandra:4.0
    ports:
      - '9042:9042'
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
    environment:
        CASSANDRA_CLUSTER_NAME: 'busrush'
    networks:
        - bus-net




volumes:
  busrush-db:

networks:
  bus-net: