version: '3.9'

services:
  app:
    container_name: busrush
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/busrush
    # environment:
    #  FLASK_DEBUG: True
    networks:
      - bus-net
  mysql-db:
    container_name: busrush-db
    image: mysql/mysql-server:5.7
    ports:
      - '3306:3306'
    volumes:
      - busrush-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: busrush
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - bus-net

volumes:
  busrush-db:

networks:
  bus-net: